name: Artifact links comments creator
on:
  workflow_run:
    workflows: ["PR"]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: Add artifact links to PR and issues
    runs-on: ubuntu-22.04
    steps:
      - name: Get information about the original PR
        uses: potiuk/get-workflow-origin@v1_5
        id: get-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
      - name: Add artifact links to PR and issues
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "**Do you want to test this code? Here you have an automated build:**"
          suffix: |
            - See: https://www.youtube.com/watch?v=I1uN9CN30gw for instructions about installing this unified targets!
            - An easier way to test this, using the Configurator cloud build, is simply put `#${{ steps.get-info.outputs.pullRequestNumber }}` (this pull request number) in the `Select commit` field of the Configurator firmware flasher tab (you need to `Enable expert mode`, `Show release candidates` and `Development`).

            _**WARNING:** It may be unstable. Use only for testing!_
          format: name
          addTo: pull
